### PR TITLE
add TNA API

### PR DESCRIPTION
**Pull request by charlesbaird-dsa**

### CODE REVIEW

**Review by odlp — COMMENTED** [review]
Nice tidyup of the trailing whitespaces 👍 

The National Archice API seems to have two URLs in the 'documentation column:

```
https://discovery.nationalarchives.gov.uk/API/sandbox/index#!/ http://www.nationalarchives.gov.uk/help/discovery-for-developers-about-the-application-programming-interface-api/
```

Which means the link doesn't work at the moment. Should this just be 1 URL, or shall I create an issue to handle multiple URLs in one column?

**Comment by charlesbaird-dsa** [comment]
> Nice tidyup of the trailing whitespaces 👍
> 
> The National Archice API seems to have two URLs in the 'documentation' column:
> 
> ```
> https://discovery.nationalarchives.gov.uk/API/sandbox/index#!/ http://www.nationalarchives.gov.uk/help/discovery-for-developers-about-the-application-programming-interface-api/
> ```
> 
> Which means the (single) link doesn't work on the rendered page. Should this just be 1 URL, or shall I create an issue to handle multiple URLs in one column?

I think that's a good idea - you'll notice that HMRC often include production / sandbox endpoints in their url field as well, it'd be useful if we had a method to deal with it.

**Comment by charlesbaird-dsa** [comment]
> > Nice tidyup of the trailing whitespaces 👍
> > The National Archice API seems to have two URLs in the 'documentation' column:
> > ```
> > https://discovery.nationalarchives.gov.uk/API/sandbox/index#!/ http://www.nationalarchives.gov.uk/help/discovery-for-developers-about-the-application-programming-interface-api/
> > ```
> > 
> > 
> > Which means the (single) link doesn't work on the rendered page. Should this just be 1 URL, or shall I create an issue to handle multiple URLs in one column?
> 
> I think that's a good idea - you'll notice that HMRC often include production / sandbox endpoints in their url field as well, it'd be useful if we had a method to deal with it.

But actually I'll edit that because I notice the first one is actually a sandbox url...

**Review by odlp — APPROVED** [review]
Thanks for fixing the documentation / sandbox URLs 👍

**Pull request merged**
